### ISSUE TITLE
Write DICOM-RT

### ISSUE THREAD

**Issue by MB-Mtl** [pieper/pydicom#2]
Any code snippet/examples showing:

1. Load a DICOM file.
2. Given a set of numpy arrays containing contour points for a handful of ROIs, write an RT struct to that DICOM, saving it as a DICOM-RT

Been pulling my hair out trying to find how to do this.

**Comment by pieper** [comment]
This is just a private fork - you might file something at the official pydicom site for help.

It may be overkill, but if you get 3D Slicer and install the SlicerRT extension you can do all kinds of RT manipulations.
